# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 481c66832b0ee47509407f0f46542026f6f5de4e7e8c9bcec75768b8d7cd9cb845f74928430b7aad266d2eaae2885f529892248863b2708a7356e39697bf1e03

test:
  secret_key_base: 926d6b6a30fb856693ad5c0212b0cd56516d69769a0c80f099faf56c00a00ca8edd50cda0d5f02e551d3df529d6122d27534874bcf83a10603ea1664b58b4c3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
